use_frameworks!

target 'DrawVCUtil_Example' do
  pod 'DrawVCUtil', :path => '../'

  target 'DrawVCUtil_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
